// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_autocorrelation_1
NumericVector c_autocorrelation_1(NumericVector x);
RcppExport SEXP _ConMK_c_autocorrelation_1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c_autocorrelation_1(x));
    return rcpp_result_gen;
END_RCPP
}
// mann_kendall_S
NumericVector mann_kendall_S(NumericMatrix x);
RcppExport SEXP _ConMK_mann_kendall_S(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mann_kendall_S(x));
    return rcpp_result_gen;
END_RCPP
}
// c_contextual_mann_kendall
List c_contextual_mann_kendall(NumericMatrix x, int nrow, int neighbourhood);
RcppExport SEXP _ConMK_c_contextual_mann_kendall(SEXP xSEXP, SEXP nrowSEXP, SEXP neighbourhoodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type neighbourhood(neighbourhoodSEXP);
    rcpp_result_gen = Rcpp::wrap(c_contextual_mann_kendall(x, nrow, neighbourhood));
    return rcpp_result_gen;
END_RCPP
}
// c_mann_kendall_test
List c_mann_kendall_test(NumericVector x);
RcppExport SEXP _ConMK_c_mann_kendall_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c_mann_kendall_test(x));
    return rcpp_result_gen;
END_RCPP
}
// c_mann_kendall_test_and_beta
List c_mann_kendall_test_and_beta(NumericVector x, NumericVector t);
RcppExport SEXP _ConMK_c_mann_kendall_test_and_beta(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(c_mann_kendall_test_and_beta(x, t));
    return rcpp_result_gen;
END_RCPP
}
// neighbour_cells_queen_row_col
IntegerVector neighbour_cells_queen_row_col(int i, int nrow, int ncol);
RcppExport SEXP _ConMK_neighbour_cells_queen_row_col(SEXP iSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbour_cells_queen_row_col(i, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// neighbour_cells_queen_col_row
IntegerVector neighbour_cells_queen_col_row(int i, int nrow, int ncol);
RcppExport SEXP _ConMK_neighbour_cells_queen_col_row(SEXP iSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbour_cells_queen_col_row(i, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// forward_neighbour_cells_queen_row_col
IntegerVector forward_neighbour_cells_queen_row_col(int i, int nrow, int ncol);
RcppExport SEXP _ConMK_forward_neighbour_cells_queen_row_col(SEXP iSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_neighbour_cells_queen_row_col(i, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// forward_neighbour_cells_queen_col_row
IntegerVector forward_neighbour_cells_queen_col_row(int i, int nrow, int ncol);
RcppExport SEXP _ConMK_forward_neighbour_cells_queen_col_row(SEXP iSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_neighbour_cells_queen_col_row(i, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _ConMK_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// c_theil_sen_vector
NumericVector c_theil_sen_vector(NumericVector x, NumericVector t);
RcppExport SEXP _ConMK_c_theil_sen_vector(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(c_theil_sen_vector(x, t));
    return rcpp_result_gen;
END_RCPP
}
// c_wang_swail_prewithen_1d
List c_wang_swail_prewithen_1d(NumericVector x, NumericVector t, double eps, double rho_th, int itmax);
RcppExport SEXP _ConMK_c_wang_swail_prewithen_1d(SEXP xSEXP, SEXP tSEXP, SEXP epsSEXP, SEXP rho_thSEXP, SEXP itmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type rho_th(rho_thSEXP);
    Rcpp::traits::input_parameter< int >::type itmax(itmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(c_wang_swail_prewithen_1d(x, t, eps, rho_th, itmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ConMK_c_autocorrelation_1", (DL_FUNC) &_ConMK_c_autocorrelation_1, 1},
    {"_ConMK_mann_kendall_S", (DL_FUNC) &_ConMK_mann_kendall_S, 1},
    {"_ConMK_c_contextual_mann_kendall", (DL_FUNC) &_ConMK_c_contextual_mann_kendall, 3},
    {"_ConMK_c_mann_kendall_test", (DL_FUNC) &_ConMK_c_mann_kendall_test, 1},
    {"_ConMK_c_mann_kendall_test_and_beta", (DL_FUNC) &_ConMK_c_mann_kendall_test_and_beta, 2},
    {"_ConMK_neighbour_cells_queen_row_col", (DL_FUNC) &_ConMK_neighbour_cells_queen_row_col, 3},
    {"_ConMK_neighbour_cells_queen_col_row", (DL_FUNC) &_ConMK_neighbour_cells_queen_col_row, 3},
    {"_ConMK_forward_neighbour_cells_queen_row_col", (DL_FUNC) &_ConMK_forward_neighbour_cells_queen_row_col, 3},
    {"_ConMK_forward_neighbour_cells_queen_col_row", (DL_FUNC) &_ConMK_forward_neighbour_cells_queen_col_row, 3},
    {"_ConMK_rcpp_hello", (DL_FUNC) &_ConMK_rcpp_hello, 0},
    {"_ConMK_c_theil_sen_vector", (DL_FUNC) &_ConMK_c_theil_sen_vector, 2},
    {"_ConMK_c_wang_swail_prewithen_1d", (DL_FUNC) &_ConMK_c_wang_swail_prewithen_1d, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConMK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
