# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_autocorrelation_1 <- function(x) {
    .Call('_ConMK_c_autocorrelation_1', PACKAGE = 'ConMK', x)
}

mann_kendall_S <- function(x) {
    .Call('_ConMK_mann_kendall_S', PACKAGE = 'ConMK', x)
}

c_contextual_mann_kendall <- function(x, nrow, neighbourhood = 2L) {
    .Call('_ConMK_c_contextual_mann_kendall', PACKAGE = 'ConMK', x, nrow, neighbourhood)
}

c_mann_kendall_test <- function(x) {
    .Call('_ConMK_c_mann_kendall_test', PACKAGE = 'ConMK', x)
}

c_mann_kendall_test_and_beta <- function(x, t) {
    .Call('_ConMK_c_mann_kendall_test_and_beta', PACKAGE = 'ConMK', x, t)
}

neighbour_cells_queen_row_col <- function(i, nrow, ncol) {
    .Call('_ConMK_neighbour_cells_queen_row_col', PACKAGE = 'ConMK', i, nrow, ncol)
}

neighbour_cells_queen_col_row <- function(i, nrow, ncol) {
    .Call('_ConMK_neighbour_cells_queen_col_row', PACKAGE = 'ConMK', i, nrow, ncol)
}

forward_neighbour_cells_queen_row_col <- function(i, nrow, ncol) {
    .Call('_ConMK_forward_neighbour_cells_queen_row_col', PACKAGE = 'ConMK', i, nrow, ncol)
}

forward_neighbour_cells_queen_col_row <- function(i, nrow, ncol) {
    .Call('_ConMK_forward_neighbour_cells_queen_col_row', PACKAGE = 'ConMK', i, nrow, ncol)
}

rcpp_hello <- function() {
    .Call('_ConMK_rcpp_hello', PACKAGE = 'ConMK')
}

c_theil_sen_vector <- function(x, t) {
    .Call('_ConMK_c_theil_sen_vector', PACKAGE = 'ConMK', x, t)
}

c_wang_swail_prewithen_1d <- function(x, t, eps, rho_th, itmax) {
    .Call('_ConMK_c_wang_swail_prewithen_1d', PACKAGE = 'ConMK', x, t, eps, rho_th, itmax)
}

